export default (
  <svg
    width="100%"
    height="100%"
    viewBox="0 0 64 64"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle
      id="e"
      className="ring"
      fill="none"
      stroke="currentColor"
      strokeWidth="4.5"
      cx="17.152"
      cy="32"
      r="15"
    />
    <circle
      id="s"
      className="ring"
      fill="none"
      stroke="currentColor"
      strokeWidth="4.5"
      cx="32"
      cy="46.839"
      r="15"
    />
    <circle
      id="w"
      className="ring"
      fill="none"
      stroke="currentColor"
      strokeWidth="4.5"
      cx="46.848"
      cy="32"
      r="15"
    />
    <circle
      id="n"
      className="ring"
      fill="none"
      stroke="currentColor"
      strokeWidth="4.5"
      cx="32"
      cy="17.152"
      r="15"
    />
  </svg>
);
