const strings = {
    months: "Months",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    accept_all: "Accept all",
    all_cookies: "All cookies",
    all_cookies_info: "Enable all cookies.",
    advertising_cookies: "Advertising cookies",
    advertising_cookies_info: "We use cookies to serve ads.",
    form_line_1: "Ready to meet?",
    form_line_2: "No time-wasting, just dating.",
    follow_us: "Follow us!",
    contact_us: "Contact us",
    cookies: "Cookies",
    cookie_settings: "Cookie settings",
    cookie_settings_text:
        "Both Timeling aswell as our partners use tools to understand our audience better and enhance the experience of the App. These tools allow us to provide features such as authentication.",
    cookies_consent: "By using our website, you agree to our cookie policy.",
    cookies_text:
        "We use cookies to help improve your experience on our website. This cookie policy is part of Timeling Limited's privacy policy, and covers the use of cookies between your device and our site.",
    coming_soon: "Coming soon",
    email: "Email",
    female: "Female",
    headline: "Date in real life",
    headline_sub: "Your calendar-based dating app for real life connections.",
    headline_sub2:
        "Sign up and get the exclusive chance to win a spot at our launch party at Sawan, Oslo.",
    headline_sub2_short: "Sign up and get the chance to join our launch party. ",
    dont_miss_out: "Don't miss out!",
    male: "Male",
    name: "Name",
    i_agree_to_the_0: "I agree to the {0}",
    by_click_0_you_agree_to_1: "By clicking {0} you are accepting our {1}",
    its_about_time: "It's about time.",
    notify_me: "Notify me",
    lets_meet_up: "Let's meet up",
    other: "Other",
    join_now: "Join now",
    join_the_waitlist: "Join waitlist",
    read_more: "Read more",
    save_preferences: "Save preferences",
    set_preferences: "Set preferences",
    scroll_dates_title: "Scroll dates,{0}not profiles",
    scroll_dates_content_short:
        "The dating app for, well, dates. Say goodbye to endless chatting and time-wasting.",
    scroll_dates_content_long:
        "Timeling is a calendar-based meet-up app that lets you set and go on dates. This saves you endless chatting, clashing expectations or ghosting – and helps you to actually meet new people, friends and maybe even the love of your life. So, stop swiping and start dating.",
    terms_of_service: "Terms of service",
    privacy_policy: "Privacy policy",
    press_realease: "Press release",
    time_we_met_title: "It's time we met",
    time_we_met_content_short:
        "Online dating, the Timeling way: Simply create a date, see who likes it and choose a match. Simple as that.",
    time_we_met_content_long:
        "A new kind of online dating: With Timeling, you can create a date, see who likes it and choose a match. Then you can chat or call to test the waters, confirm and meet up. No more wasting time, no more frustration. It’s a dating app with an active deadline, so to say.",
    ladies_first_title: "Say goodbye to bad dates",
    ladies_first_content_short:
        "We want you to enjoy your time with Timeling. That’s why we’ve developed a system that lets you confidentially share your experience with our admins.",
    ladies_first_content_long:
        "We want you to enjoy your time with Timeling. That’s why we've developed a system that lets you confidentially share your experience with our admins so that we can ensure a community that doesn't waste your time.	",
    "404_status": "Not found",
    thank_you_submission_recieved: "Thank you! Your submission has been received!",
    something_went_wrong: "Something went wrong 😢",
    unsubscribe: "Unsubscribe",
    _has_been_unsubscribed: "{0} has been unsubscribed",
    we_value_your_privacy: "We value your privacy",
    home_title: "Life is short, let's meet up.",
    home_des01start: "Timeling is a",
    home_des01middle: "calendar-based app",
    home_des01end:
        "that lets you create events, explore and meet like-minded people. Go on dates and meet new friends. ",
    home_des02start: "New friends and",
    home_des02middle: "maybe even the love",
    home_des02end: "of your life.",
    home_des03start: "No time-wasting,",
    home_des03middle: "just real connections. ",
    how_title: "How does it work?",
    how_title_dec:
        "We're changing the game, by putting the dates first. Instead of swiping through an endless stream of profiles, you can just create, explore, and go on dates.",
    work_title_01: "Set an event",
    work_title_02: "See who likes it",
    work_title_03: "Test the waters",
    work_title_04: "Let’s meet up",
    work_dec_01: " Set a day, time and activity for your next event.",
    work_dec_02: "See who is interested and test the waters.",
    work_dec_03: "Chat and see if you have a good vibe before you meet.",
    work_dec_04: "Confirm the event and get ready to meet.",
    m_work_title_01: "Create",
    m_work_dec_01:
        "Set a day, time and activity for your next event. See who is interested and test the waters.",
    m_work_title_02: "Explore",
    m_work_dec_02: "Find and filter events near you. Drop a like to show you’re interested!",
    m_work_title_03: "Confirm",
    m_work_dec_03: "Show interest, check your likes and make matches. It's time to meet!",
};

export default strings;
