const strings = {
    accept_all: "Aksepter alt",
    set_preferences: "Angi preferanser",
    months: "Måneder",
    days: "Dager",
    hours: "Timer",
    minutes: "Minutter",
    seconds: "Sekunder",
    form_line_1: "Klar for å møtes?",
    form_line_2: "Ingen bortkastet tid – bare dating.",
    dont_miss_out: "Ikke gå glipp av dette!",
    headline_sub: "Kalenderbasert datingapp for møter i virkeligheten.",
    headline_sub2:
        "Meld deg på og få en eksklusiv mulighet til å vinne en billett til lanseringsfesten vår på Sawan i Oslo.",
    headline_sub2_short: "Meld deg på og få sjansen til å bli med på lanseringsfesten vår.",
    follow_us: "Følg oss!",
    coming_soon: "Kommer snart",
    contact_us: "Kontakt oss",
    cookies: "Cookies",
    cookies_consent: "Ved å bruke vår nettside godtar du vår bruk av cookies. ",
    cookies_text:
        "Vi bruker cookies for å forbedre opplevelsen din på vår nettside. Dette inkluderer analyse- og annonse-cookies. For mer informasjon, se vår Cookie-side. ",
    email: "Epost",
    female: "Kvinne",
    headline: "Date i det virkelige liv.",
    male: "Mann",
    name: "Navn",
    i_agree_to_the_0: "Jeg godtar {0}",
    by_click_0_you_agree_to_1: 'Ved å klikke på "bli med nå" aksepterer du våre betingelser',
    its_about_time: "Tiden er inne.",
    notify_me: "Varsle meg",
    lets_meet_up: "La oss møtes",
    other: "Annet",
    join_now: "Bli med nå",
    join_the_waitlist: "Meld deg på ventelisten",
    scroll_dates_title: "Finn dater, ikke profiler",
    scroll_dates_content_short:
        "Datingappen for... Vel... Dater! Si farvel til endeløs chatting og bortkastet tid.",
    scroll_dates_content_long:
        "Timeling er en kalenderbasert møteapp som lar deg gå på dater. Det sparer deg for endeløs chatting, ulike forventninger og ghosting - og lar deg faktisk møte nye mennesker, venner og kanskje ditt livs kjærlighet. Så slutt å sveipe, begynn å date.",
    terms_of_service: "Betingelser",
    privacy_policy: "Personvern",
    time_we_met_title: "På tide at vi møtes",
    time_we_met_content_short:
        "Nettdating på Timeling-måten: Opprett en date, se hvem som er interessert og velg en match. Så enkelt er det!",
    time_we_met_content_long:
        "En ny type nettdating: med Timeling kan du lage en date, se hvem som liker den og velge en match. Så kan dere chatte eller ringes for å bli bedre kjent, bekrefte daten og møtes. Mindre bortkastet tid og mindre frustrasjon. Det er rett og slett en datingapp med en tidsfrist.",
    ladies_first_title: "Si farvel til dårlige dater",
    ladies_first_content_short:
        "Vi vil at du skal kose deg med Timeling. Derfor har vi utviklet et system som lar deg dele din opplevelse med vårt team, helt konfidensielt.",
    ladies_first_content_long:
        "Vi vil at du skal kose deg med Timeling. Derfor har vi utviklet et system som lar deg dele din opplevelse med vårt team, helt konfidensielt. På denne måten lager vi et samfunn som ikke kaster bort tiden din. ",
    "404_status": "Ikke funnet",
    thank_you_submission_recieved: "Takk skal du ha! Innsendingen din er mottatt!",
    something_went_wrong: "Noe gikk galt 😢",
    unsubscribe: "avslutte abonnement",
    _has_been_unsubscribed: "{0} har blitt avmeldt",
    we_value_your_privacy: "Vi tar ditt personvern på alvor",
    home_title: "Life is short, let's meet up.",
    home_des01start: "Timeling is a",
    home_des01middle: "calendar-based app",
    home_des01end: "that let's you create, explore and meet like-minded people.",
    home_des02start: "New friends and",
    home_des02middle: "maybe even the love",
    home_des02end: "of your life.",
    home_des03start: "No time-wasting,",
    home_des03middle: "just real connections. ",
    how_title: "How does it work?",
    how_title_dec:
        "We're changing the game, by putting the dates first. Instead of swiping through an endless stream of profiles, you can just create, explore, and go on dates.",
    work_title_01: "Set an event",
    work_title_02: "See who likes it",
    work_title_03: "Test the waters",
    work_title_04: "Let’s meet up",
    work_dec_01: " Set a day, time and activity for your next event.",
    work_dec_02: "See who is interested and test the waters.",
    work_dec_03: "Chat and see if you have a good vibe before you meet.",
    work_dec_04: "Confirm the event and get ready to meet.",
    m_work_title_01: "Create",
    m_work_dec_01:
        "Set a day, time and activity for your next event. See who is interested and test the waters.",
    m_work_title_02: "Explore",
    m_work_dec_02: "Find and filter events near you. Drop a like to show you’re interested!",
    m_work_title_03: "Confirm",
    m_work_dec_03: "Show interest, check your likes and make matches. It's time to meet!",
};
export default strings;
